name: ⚙️ Setup Config for Server (NextJS)

on:
  workflow_dispatch:

concurrency:
  group: "deploy-prod-iiitnr"
  cancel-in-progress: false

jobs:
  deploy:
    name: Update the Remote Server
    runs-on: ubuntu-latest

    steps:  
      - name: ⚙️ Update Nginx config & reload
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.SSH_PORT }}
            script: |
                echo "Updating Nginx config..."
                sudo tee /etc/nginx/sites-available/${{ secrets.PROJECT_ID }} > /dev/null <<'EOF'
         
                server {
                  listen 80;
                  listen [::]:80;
                  server_name ${{ secrets.PROJECT_SUBDOMAIN }}.iiitnr.ac.in;
                  return 301 https://$host$request_uri;
                }

                server {
                  listen 443 ssl http2;
                  listen [::]:443 ssl http2;

                  server_name ${{ secrets.PROJECT_SUBDOMAIN }}.iiitnr.ac.in;

                  ssl_certificate     /home/${{ secrets.SSH_USER }}/ssl_certificate/ssl_certificate.crt;
                  ssl_certificate_key /home/${{ secrets.SSH_USER }}/ssl_certificate/ssl_key.key;
                  ssl_protocols       TLSv1.2 TLSv1.3;
                  ssl_ciphers         HIGH:!aNULL:!MD5;

                  location / {
                    proxy_pass http://127.0.0.1:3000;

                    # WebSocket and reverse proxy headers
                    proxy_http_version 1.1;
                    proxy_set_header Upgrade $http_upgrade;
                    proxy_set_header Connection 'upgrade';
                    proxy_set_header Host $host;
                    proxy_cache_bypass $http_upgrade;
                  }
                }
                EOF

                echo "Enabling site & reloading Nginx..."
                sudo ln -sf /etc/nginx/sites-available/${{ secrets.PROJECT_ID }} /etc/nginx/sites-enabled/
                sudo nginx -t
                sudo systemctl reload nginx
